'plugin: babel':
  - changed-files:
      - any-glob-to-any-file: 'packages/babel/**'

'plugin: emotion':
  - changed-files:
      - any-glob-to-any-file: 'packages/emotion/**'

'plugin: jsx-remove-attributes':
  - changed-files:
      - any-glob-to-any-file: 'packages/jsx-remove-attributes/**'

'plugin: styled-jsx':
  - changed-files:
      - any-glob-to-any-file: 'packages/styled-jsx/**'

'plugin: transform-imports':
  - changed-files:
      - any-glob-to-any-file: 'packages/transform-imports/**'

'package: oxc-unshadowed-visitor':
  - changed-files:
      - any-glob-to-any-file: 'packages/oxc-unshadowed-visitor/**'
