packages:
  - packages/*
  - packages/*/benchmark
  - internal-packages/*
  - examples
  - examples/*
  - scripts

allowBuilds:
  '@swc/core': true
  esbuild: true
  playwright-chromium: true

catalogs:
  default:
    '@oxc-node/core': ^0.1.0
    '@oxc-node/cli': ^0.1.0
    '@rollup/plugin-swc': ^0.4.1
    '@swc/core': ^1.15.43
    '@swc/plugin-emotion': ^14.14.0
    '@swc/plugin-react-remove-properties': ^12.14.0
    '@swc/plugin-styled-jsx': ^13.14.0
    '@swc/plugin-transform-imports': ^12.14.0
    rolldown: ^1.0.2
    vite: ^8.0.14
  babel7:
    '@babel/core': ^7.29.7
    '@babel/plugin-transform-runtime': ^7.29.7
    '@babel/runtime': ^7.29.7
