packages:
  - packages/*
  - packages/*/benchmark
  - internal-packages/*
  - examples
  - examples/*
  - scripts

allowBuilds:
  '@swc/core': true
  playwright-chromium: true

catalogs:
  babel7:
    '@babel/core': ^7.29.0
    '@babel/plugin-transform-runtime': ^7.29.0
    '@babel/runtime': ^7.29.2
