name: "\U0001F680 New feature proposal"
description: Propose a new feature to be added to a plugin in this repository
labels: ['pending triage']
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: checkboxes
    id: plugins
    attributes:
      label: Related plugins
      description: Select the plugin which is related
      options:
        - label: |-
            [plugin-babel](https://github.com/rolldown/plugins/tree/main/packages/babel)
        - label: |-
            [plugin-emotion](https://github.com/rolldown/plugins/tree/main/packages/emotion)
        - label: |-
            [plugin-jsx-remove-attributes](https://github.com/rolldown/plugins/tree/main/packages/jsx-remove-attributes)
        - label: |-
            [plugin-styled-jsx](https://github.com/rolldown/plugins/tree/main/packages/styled-jsx)
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!'
      placeholder: As a developer using [plugin name] plugin, I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'In module [xy] we could provide following implementation...'
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/rolldown/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
