name: Publish Package

on:
  push:
    tags:
      - 'plugin-*'
      - 'oxc-unshadowed-visitor@*'

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'rolldown/plugins'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1

      - name: Set node version to LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          # disable cache, to avoid cache poisoning (https://docs.zizmor.sh/audits/#cache-poisoning)
          package-manager-cache: false

      - name: Disallow installation scripts
        run: yq '.onlyBuiltDependencies = []' -i pnpm-workspace.yaml

      - name: Install deps
        run: pnpm install

      - name: Publish package
        run: npm i -g npm@^11.5.2 && pnpm run ci-publish ${{ github.ref_name }}
